[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ukrainian_stressifier_byt5_ct2"
version = "0.1.0"
description = "Ukrainian stress prediction using ByT5 and CTranslate2"
readme = "README.md"
requires-python = ">=3.8"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["."]
include = ["ukrainian_stressifier_byt5_ct2*"]
